-- Touchup V2 Migration
-- Redesign: Per-volume interactive workflow (separate Touchup tab)
--
-- Changes:
--   1. touchup_analyses.status: simplified to ('active', 'completed') — session container
--   2. touchup_volumes.status:  add 'scored' state between scoring and rewriting
--   3. touchup_analyses.status default: 'active' instead of 'pending'
--
-- Run this after supabase-touchup-draft-migration.sql.
-- Safe to re-run.

-----------------------------------------------------------
-- 1. Update existing touchup_analyses rows to new statuses
-----------------------------------------------------------

UPDATE touchup_analyses
SET status = 'active'
WHERE status IN ('pending', 'scoring', 'rewriting', 'failed');

-- 'completed' stays as 'completed'

-----------------------------------------------------------
-- 2. Alter touchup_analyses.status CHECK constraint
-----------------------------------------------------------

DO $$ BEGIN
  -- Drop old constraint (name auto-generated by Postgres: tablename_columnname_check)
  ALTER TABLE touchup_analyses DROP CONSTRAINT IF EXISTS touchup_analyses_status_check;
EXCEPTION WHEN undefined_object THEN
  NULL;
END $$;

ALTER TABLE touchup_analyses
  ADD CONSTRAINT touchup_analyses_status_check
  CHECK (status IN ('active', 'completed'));

ALTER TABLE touchup_analyses
  ALTER COLUMN status SET DEFAULT 'active';

-----------------------------------------------------------
-- 3. Alter touchup_volumes.status CHECK constraint
--    Add 'scored' between 'scoring' and 'rewriting'
-----------------------------------------------------------

DO $$ BEGIN
  ALTER TABLE touchup_volumes DROP CONSTRAINT IF EXISTS touchup_volumes_status_check;
EXCEPTION WHEN undefined_object THEN
  NULL;
END $$;

ALTER TABLE touchup_volumes
  ADD CONSTRAINT touchup_volumes_status_check
  CHECK (status IN ('pending', 'scoring', 'scored', 'rewriting', 'completed', 'failed'));
